### ISSUE TITLE
Flakey Test: wick_run

### ISSUE THREAD

**Issue by fawadasaurus** [candlecorp/wick#163]
**Describe the bug**
This test sometimes works and sometimes fails

**To Reproduce**
Run test in GitHub actions. When test fails, retry failed and it might work.

**Expected behavior**
No fail should occur.

**Actual behavior**
```
---- wick_run stdout ----
[1355](https://github.com/candlecorp/wick/actions/runs/4484348604/jobs/7884750622#step:12:1356)
2023-03-21T22:39:01 TRACE Logger initialized
[1356](https://github.com/candlecorp/wick/actions/runs/4484348604/jobs/7884750622#step:12:1357)
2023-03-21T22:39:01 DEBUG Writing logs to /home/runner/.local/state/wick/logs
[1357](https://github.com/candlecorp/wick/actions/runs/4484348604/jobs/7884750622#step:12:1358)
2023-03-21T22:39:01 DEBUG load as file location="./manifests/log.yaml"
[1358](https://github.com/candlecorp/wick/actions/runs/4484348604/jobs/7884750622#step:12:1359)
2023-03-21T22:39:01 TRACE bytes include wasm header? is_wasm=false bytes=[45, 45, 45, 10]
[1359](https://github.com/candlecorp/wick/actions/runs/4484348604/jobs/7884750622#step:12:1360)
error: test failed, to rerun pass `-p wick --test run`
[1360](https://github.com/candlecorp/wick/actions/runs/4484348604/jobs/7884750622#step:12:1361)
2023-03-21T22:39:01 DEBUG rest args args=[]
[1361](https://github.com/candlecorp/wick/actions/runs/4484348604/jobs/7884750622#step:12:1362)
2023-03-21T22:39:01 DEBUG local_cli_opts.allow_latest false
[1362](https://github.com/candlecorp/wick/actions/runs/4484348604/jobs/7884750622#step:12:1363)
2023-03-21T22:39:01 DEBUG def.host.allow_latest false
[1363](https://github.com/candlecorp/wick/actions/runs/4484348604/jobs/7884750622#step:12:1364)
2023-03-21T22:39:02 TRACE network: init config=NetworkInit { definition: ComponentConfiguration { source: Some("./manifests/log.yaml"), format: 0, version: "", host: HostConfig { allow_latest: false, insecure_registries: [], timeout: 0ns, id: None, mesh: None, rpc: Some(HttpConfig { enabled: false, port: None, address: None, pem: None, key: None, ca: None }) }, name: None, types: [], labels: {}, import: {}, operations: {"logger": FlowOperation { name: "logger", inputs: [], outputs: [], instances: {"logger": InstanceReference { name: "core::log", namespace: "wick", data: None }}, connections: [ConnectionDefinition { from: ConnectionTargetDefinition { target: PortReference { instance: "<input>", port: "schem_input" }, data: None }, to: ConnectionTargetDefinition { target: PortReference { instance: "logger", port: "input" }, data: None }, default: None }, ConnectionDefinition { from: ConnectionTargetDefinition { target: PortReference { instance: "logger", port: "output" }, data: None }, to: ConnectionTargetDefinition { target: PortReference { instance: "<output>", port: "schem_output" }, data: None }, default: None }], collections: [], constraints: {} }} }, allow_latest: false, allowed_insecure: [], timeout: 5s, namespace: Some("4eeae4b0-1bcb-4b13-9af5-1c8dd530b729"), rng_seed: Seed(14209941976422297445) }
[1364](https://github.com/candlecorp/wick/actions/runs/4484348604/jobs/7884750622#step:12:1365)
2023-03-21T22:39:02 TRACE network:initialize_native_collection{namespace="wick"}: registering
[1365](https://github.com/candlecorp/wick/actions/runs/4484348604/jobs/7884750622#step:12:1366)
2023-03-21T22:39:02 TRACE network signature signature=ComponentSignature { name: Some("0c46c204-3ff8-9850-be78-48618588065a"), format: V1, metadata: ComponentMetadata { version: None }, wellknown: [], types: [], operations: [OperationSignature { name: "logger", inputs: [Field { name: "schem_input", ty: String, default: None, required: false, description: None }, Field { name: "schem_input", ty: Value, default: None, required: false, description: None }], outputs: [Field { name: "schem_output", ty: String, default: None, required: false, description: None }, Field { name: "schem_output", ty: Value, default: None, required: false, description: None }] }], config: [] }
[1366](https://github.com/candlecorp/wick/actions/runs/4484348604/jobs/7884750622#step:12:1367)
2023-03-21T22:39:02 DEBUG cli:args:port-data port="schem_input" value="\"testing123\""
[1367](https://github.com/candlecorp/wick/actions/runs/4484348604/jobs/7884750622#step:12:1368)
2023-03-21T22:39:02 TRACE invocation start start_time=1679438342019
[1368](https://github.com/candlecorp/wick/actions/runs/4484348604/jobs/7884750622#step:12:1369)
2023-03-21T22:39:02 TRACE invocation complete duration_ms=1
[1369](https://github.com/candlecorp/wick/actions/runs/4484348604/jobs/7884750622#step:12:1370)
2023-03-21T22:39:02 TRACE stdlib invoke: wick://wick.coll/core::log
[1370](https://github.com/candlecorp/wick/actions/runs/4484348604/jobs/7884750622#step:12:1371)
2023-03-21T22:39:02 TRACE stdlib result: wick://wick.coll/core::log
[1371](https://github.com/candlecorp/wick/actions/runs/4484348604/jobs/7884750622#step:12:1372)
thread 'tokio-runtime-worker' panicked at 'port should never be pushed to after being closed.', crates/wick/flow-graph-interpreter/src/interpreter/executor/transaction/operation/port/port_handler.rs:85:5
[1372](https://github.com/candlecorp/wick/actions/runs/4484348604/jobs/7884750622#step:12:1373)
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
[1373](https://github.com/candlecorp/wick/actions/runs/4484348604/jobs/7884750622#step:12:1374)
2023-03-21T22:39:02 TRACE output Packet { metadata: Metadata { index: 0, extra: None }, extra: WickMetadata { flags: 128, port: "schem_output" }, payload: Ok(b"") }
[1374](https://github.com/candlecorp/wick/actions/runs/4484348604/jobs/7884750622#step:12:1375)
2023-03-21T22:39:02 TRACE stream complete
[1375](https://github.com/candlecorp/wick/actions/runs/4484348604/jobs/7884750622#step:12:1376)
2023-03-21T22:39:02 DEBUG host stopping
[1376](https://github.com/candlecorp/wick/actions/runs/4484348604/jobs/7884750622#step:12:1377)
2023-03-21T22:39:02 TRACE network shutting down
[1377](https://github.com/candlecorp/wick/actions/runs/4484348604/jobs/7884750622#step:12:1378)

[1378](https://github.com/candlecorp/wick/actions/runs/4484348604/jobs/7884750622#step:12:1379)
thread 'wick_run' panicked at 'called `Option::unwrap()` on a `None` value', crates/bins/wick/tests/run.rs:21:8
[1379](https://github.com/candlecorp/wick/actions/runs/4484348604/jobs/7884750622#step:12:1380)
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
[1380](https://github.com/candlecorp/wick/actions/runs/4484348604/jobs/7884750622#step:12:1381)

[1381](https://github.com/candlecorp/wick/actions/runs/4484348604/jobs/7884750622#step:12:1382)

[1382](https://github.com/candlecorp/wick/actions/runs/4484348604/jobs/7884750622#step:12:1383)
failures:
[1383](https://github.com/candlecorp/wick/actions/runs/4484348604/jobs/7884750622#step:12:1384)
    wick_run
    ```

**Environment:**
 - OS: linux
 - Architecture: amd64
 - Build Version: main

**Additional context**

**Comment by jsoverson** [comment]
This test has been ported to trycmd style in #167 so this error won't pop up anymore.
